"""add initiated_by

Revision ID: 224531b0b470
Revises: 9bc6e88d804f
Create Date: 2026-01-02 22:04:50.737161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224531b0b470'
down_revision = '9bc6e88d804f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initiated_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_connection_initiated_by_user', 'user', ['initiated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('initiated_by')

    # ### end Alembic commands ###
